build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7

install:
  - pip install -r requirements.txt
  - pip install pylint

test_script:
  - python pylint-recursive.py
  - python -m unittest discover -v -p "*_test.py"
